/**
 * components/QueryResultPanel.jsx — Premium Claymorphism renderer
 * Handles: success, dry_run, rejected, error states.
 */
import { useState } from 'react';
import { CheckCircle2, XCircle, AlertTriangle, ChevronRight, Info, Lightbulb, Database, MessageSquare, Sparkles } from 'lucide-react';
import KpiCard from './KpiCard';
import StatusBadge from './StatusBadge';
import SqlViewer from './SqlViewer';
import LineageGraph from './LineageGraph';

const CLAY_SHADOW = `16px 16px 32px rgba(13,148,136,0.12), -10px -10px 24px rgba(255,255,255,0.9), inset 6px 6px 12px rgba(13,148,136,0.04), inset -6px -6px 12px rgba(255,255,255,1)`;
const CLAY_INSET  = `inset 8px 8px 16px rgba(13,148,136,0.08), inset -8px -8px 16px rgba(255,255,255,0.9)`;
const CLAY_CARD   = `8px 8px 16px rgba(13,148,136,0.06), -6px -6px 12px rgba(255,255,255,0.9)`;

/* ── Conversational narrative summary ── */
function NarrativeSummary({ text, query, lineagePath }) {
  if (!text) {
    return (
      <div className="flex flex-col items-center justify-center py-10 gap-3 text-center">
        <div
          className="w-12 h-12 rounded-full flex items-center justify-center"
          style={{ background: 'rgba(13,148,136,0.08)', boxShadow: 'inset 3px 3px 6px rgba(13,148,136,0.10), inset -3px -3px 6px rgba(255,255,255,0.9)' }}
        >
          <MessageSquare size={20} className="text-[#0D9488]" />
        </div>
        <p className="text-[#4A7B76] text-sm" style={{ fontFamily: 'DM Sans, sans-serif' }}>
          No conversational summary available for this result.
        </p>
      </div>
    );
  }

  return (
    <div className="flex flex-col gap-5">
      <div className="flex items-start gap-3">
        <div
          className="w-8 h-8 rounded-full flex items-center justify-center shrink-0"
          style={{ background: 'linear-gradient(135deg, #0D9488 0%, #059669 100%)', boxShadow: '3px 3px 8px rgba(13,148,136,0.25)' }}
        >
          <Sparkles size={14} className="text-white" />
        </div>
        <div
          className="px-5 py-4 rounded-[20px] rounded-tl-[4px] text-sm text-[#1A3A38] leading-relaxed max-w-[85%] animate-fade-in"
          style={{ background: 'rgba(255,255,255,0.75)', boxShadow: CLAY_CARD, fontFamily: 'DM Sans, sans-serif' }}
        >
          {text.split(/(\*\*.*?\*\*)/g).map((part, i) => {
            if (part.startsWith('**') && part.endsWith('**')) {
              return <strong key={i} className="text-[#0D9488] font-black">{part.slice(2, -2)}</strong>;
            }
            return part;
          })}
        </div>
      </div>
      {lineagePath?.length > 0 && (
        <div className="mt-2 text-xs text-[#4A7B76] font-mono bg-[rgba(255,255,255,0.5)] px-4 py-2 rounded-[12px] border border-[#0D9488]/10 w-fit">
          <span className="font-sans font-bold text-[#0D9488] uppercase text-[10px] tracking-wider mr-2">Lineage Trace:</span>
          {lineagePath.join(' → ')}
        </div>
      )}
      <p className="text-[10px] text-[#4A7B76]/60 text-center mt-1" style={{ fontFamily: 'DM Sans, sans-serif' }}>
        This summary was generated by AI from certified data. Always validate against the Results tab.
      </p>
    </div>
  );
}

/* ── Tabs ── */
function Tabs({ tabs, active, onSelect }) {
  return (
    <div className="tab-track">
      {tabs.map((t) => (
        <button
          key={t}
          onClick={() => onSelect(t)}
          className={active === t ? 'tab-btn-active' : 'tab-btn'}
        >
          {t}
        </button>
      ))}
    </div>
  );
}

/* ── Results table ── */
function ResultsTable({ data }) {
  const [showAll, setShowAll] = useState(false);

  if (!data || data.length === 0) {
    return (
      <p className="text-neu-muted text-sm font-dm text-center py-8">
        No data rows returned (dry run or empty result set).
      </p>
    );
  }
  const cols      = Object.keys(data[0]);
  const displayed = showAll ? data : data.slice(0, 20);

  return (
    <div className="overflow-x-auto rounded-[20px]" style={{ boxShadow: CLAY_INSET }}>
      <table className="w-full text-sm font-dm">
        <thead>
          <tr className="bg-[rgba(255,255,255,0.4)] border-b border-[#D1E2DE]/50">
            {cols.map((c) => (
              <th key={c} className="px-4 py-3 text-left text-xs font-mono text-neu-muted uppercase tracking-wide whitespace-nowrap">
                {c}
              </th>
            ))}
          </tr>
        </thead>
        <tbody className="divide-y divide-[#D1E2DE]/40">
          {displayed.map((row, i) => (
            <tr key={i} className="hover:bg-[rgba(255,255,255,0.5)] transition-colors">
              {cols.map((c) => {
                let displayValue = <span className="text-neu-muted/40">null</span>;
                if (row[c] != null) {
                  const val = row[c];
                  const cLower = c.toLowerCase();
                  if (typeof val === 'number' && (cLower.endsWith('_rate') || cLower.endsWith('_pct') || cLower.endsWith('_ctr'))) {
                    displayValue = `${(val * 100).toFixed(2)}%`;
                  } else if (typeof val === 'number' && !Number.isInteger(val)) {
                    displayValue = val.toFixed(2);
                  } else {
                    displayValue = String(val);
                  }
                }
                return (
                  <td key={c} className="px-4 py-3 text-neu-primary whitespace-nowrap font-dm">
                    {displayValue}
                  </td>
                );
              })}
            </tr>
          ))}
        </tbody>
      </table>
      {data.length > 20 && !showAll && (
        <div className="flex justify-center p-3 border-t border-[#D1E2DE]/40 bg-[rgba(255,255,255,0.2)]">
            <button 
                onClick={() => setShowAll(true)}
                className="text-xs font-bold text-[#0D9488] hover:text-[#0F766E] transition-colors"
            >
                Show all {data.length} rows
            </button>
        </div>
      )}
      {data.length > 20 && showAll && (
        <div className="flex justify-center p-3 border-t border-[#D1E2DE]/40 bg-[rgba(255,255,255,0.2)]">
            <button 
                onClick={() => setShowAll(false)}
                className="text-xs font-bold text-[#0D9488] hover:text-[#0F766E] transition-colors"
            >
                Show fewer rows
            </button>
        </div>
      )}
    </div>
  );
}

/* ── Governance tab ── */
function GovernancePanel({ governance, validation }) {
  return (
    <div className="flex flex-col gap-4">
      {governance?.warning && (
        <div
          className="flex items-start gap-3 p-4 rounded-[24px]"
          style={{ background: 'rgba(245,158,11,0.08)', boxShadow: 'inset 4px 4px 8px rgba(245,158,11,0.06), inset -4px -4px 8px rgba(255,255,255,0.9)' }}
        >
          <AlertTriangle size={16} className="text-[#F59E0B] shrink-0 mt-0.5" />
          <p className="text-[#F59E0B] text-sm" style={{ fontFamily: 'DM Sans, sans-serif' }}>{governance.warning}</p>
        </div>
      )}

      {governance?.certified_definition && (
        <div className="p-5 rounded-[24px] flex flex-col gap-1" style={{ background: 'rgba(255,255,255,0.5)', boxShadow: CLAY_CARD }}>
          <span className="text-xs text-[#4A7B76] font-bold uppercase tracking-wide block mb-1" style={{ fontFamily: 'DM Sans, sans-serif' }}>Certified Definition</span>
          <p className="text-[#1A3A38] text-sm" style={{ fontFamily: 'DM Sans, sans-serif' }}>{governance.certified_definition}</p>
        </div>
      )}

      <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
        {governance?.grain && (
          <div className="p-5 rounded-[24px]" style={{ background: 'rgba(255,255,255,0.5)', boxShadow: CLAY_CARD }}>
            <span className="text-xs text-[#4A7B76] font-bold uppercase tracking-wide block mb-1" style={{ fontFamily: 'DM Sans, sans-serif' }}>Grain</span>
            <code className="text-xs text-teal-600 font-mono">{governance.grain}</code>
          </div>
        )}
        {governance?.source_model && (
          <div className="p-5 rounded-[24px]" style={{ background: 'rgba(255,255,255,0.5)', boxShadow: CLAY_CARD }}>
            <span className="text-xs text-[#4A7B76] font-bold uppercase tracking-wide block mb-1" style={{ fontFamily: 'DM Sans, sans-serif' }}>Source Model</span>
            <code className="text-xs text-blue-600 font-mono">{governance.source_model}</code>
          </div>
        )}
      </div>

      {governance?.grain_columns?.length > 0 && (
        <div className="p-5 rounded-[24px]" style={{ background: 'rgba(255,255,255,0.5)', boxShadow: CLAY_CARD }}>
          <span className="text-xs text-[#4A7B76] font-bold uppercase tracking-wide block mb-2" style={{ fontFamily: 'DM Sans, sans-serif' }}>Grain Columns</span>
          <div className="flex flex-wrap gap-1.5">
            {governance.grain_columns.map((c) => (
              <code
                key={c}
                className="px-2 py-1 rounded-[8px] text-xs text-[#0891B2] font-mono"
                style={{ background: 'rgba(8,145,178,0.10)', boxShadow: 'inset 2px 2px 4px rgba(8,145,178,0.08), inset -2px -2px 4px rgba(255,255,255,0.9)' }}
              >
                {c}
              </code>
            ))}
          </div>
        </div>
      )}

      {validation?.checks_run?.length > 0 && (
        <div className="p-5 rounded-[24px]" style={{ background: 'rgba(255,255,255,0.5)', boxShadow: CLAY_CARD }}>
          <span className="text-xs text-[#4A7B76] font-bold uppercase tracking-wide block mb-2" style={{ fontFamily: 'DM Sans, sans-serif' }}>Governance Checks Passed</span>
          <div className="flex flex-col gap-2">
            {validation.checks_run.map((check) => (
              <div key={check} className="flex items-center gap-2 text-sm text-emerald-700">
                <CheckCircle2 size={14} className="text-emerald-500 shrink-0" />
                <span className="font-mono text-xs">{check}</span>
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  );
}

/* ── Rejection panel ── */
function RejectionPanel({ rejection }) {
  return (
    <div className="flex flex-col gap-4 animate-slide-in">
      {rejection?.violated_rules?.length > 0 && (
        <div className="p-5 rounded-[24px]" style={{ background: 'rgba(255,255,255,0.5)', boxShadow: CLAY_CARD }}>
          <span className="text-xs text-[#4A7B76] font-bold uppercase tracking-wide block mb-3" style={{ fontFamily: 'DM Sans, sans-serif' }}>Violated Rules</span>
          <div className="flex flex-wrap gap-2">
            {rejection.violated_rules.map((r) => (
              <StatusBadge key={r} status="rejected" label={r} />
            ))}
          </div>
        </div>
      )}

      {rejection?.reason && (
        <div
          className="flex items-start gap-3 p-5 rounded-[24px] backdrop-blur-xl"
          style={{ background: 'rgba(244,63,94,0.06)', boxShadow: '8px 8px 16px rgba(244,63,94,0.06), -6px -6px 12px rgba(255,255,255,0.9)' }}
        >
          <XCircle size={16} className="text-[#F43F5E] shrink-0 mt-0.5" />
          <p className="text-[#F43F5E] text-sm" style={{ fontFamily: 'DM Sans, sans-serif' }}>{rejection.reason}</p>
        </div>
      )}

      {rejection?.suggested_fix && (
        <div
          className="flex items-start gap-3 p-5 rounded-[24px] backdrop-blur-xl"
          style={{ background: 'rgba(245,158,11,0.08)', boxShadow: '8px 8px 16px rgba(245,158,11,0.06), -6px -6px 12px rgba(255,255,255,0.9)' }}
        >
          <AlertTriangle size={16} className="text-[#F59E0B] shrink-0 mt-0.5" />
          <div>
            <p className="text-xs text-[#F59E0B] font-bold uppercase tracking-wide mb-1" style={{ fontFamily: 'DM Sans, sans-serif' }}>Suggested Fix</p>
            <p className="text-[#1A3A38] text-sm" style={{ fontFamily: 'DM Sans, sans-serif' }}>{rejection.suggested_fix}</p>
          </div>
        </div>
      )}

      {rejection?.safe_alternatives?.length > 0 && (
        <div className="p-5 rounded-[24px]" style={{ background: 'rgba(255,255,255,0.5)', boxShadow: CLAY_CARD }}>
          <span className="text-xs text-[#4A7B76] font-bold uppercase tracking-wide block mb-3" style={{ fontFamily: 'DM Sans, sans-serif' }}>Safe Alternatives</span>
          <div className="flex flex-col gap-2">
            {rejection.safe_alternatives.map((alt, i) => (
              <div key={i} className="flex items-start gap-2.5">
                <ChevronRight size={14} className="text-[#0D9488] shrink-0 mt-0.5" />
                <span className="text-[#0D9488] text-sm" style={{ fontFamily: 'DM Sans, sans-serif' }}>{alt}</span>
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  );
}

/* ── Clarification panel ── */
function ClarificationPanel({ response }) {
  const { message, available_options } = response;
  return (
    <div className="flex flex-col gap-4 animate-slide-in">
      <div
        className="flex items-start gap-3 p-6 rounded-[32px] backdrop-blur-xl"
        style={{ background: 'rgba(255,255,255,0.65)', boxShadow: CLAY_SHADOW }}
      >
        <div className="bg-[#0D9488]/10 p-3 rounded-full shrink-0">
          <Info size={20} className="text-[#0D9488]" />
        </div>
        <div>
          <p className="text-[#1A3A38] text-base font-bold mb-1" style={{ fontFamily: 'DM Sans, sans-serif' }}>
            {message}
          </p>
          <p className="text-[#4A7B76] text-sm" style={{ fontFamily: 'DM Sans, sans-serif' }}>
            Please refine your question and try again.
          </p>
          
          {(available_options?.time_grains?.length > 0 || available_options?.dimensions?.length > 0) && (
            <div className="mt-5 flex flex-col gap-4">
              {available_options?.time_grains?.length > 0 && (
                <div>
                  <span className="text-[10px] text-[#4A7B76] font-bold uppercase tracking-wide block mb-2" style={{ fontFamily: 'DM Sans, sans-serif' }}>Available Time Granularities</span>
                  <div className="flex flex-wrap gap-2">
                    {available_options.time_grains.map(g => (
                      <span key={g} className="px-3 py-1 rounded-[8px] text-xs text-[#0D9488] bg-[#0D9488]/10 font-mono shadow-sm">{g}</span>
                    ))}
                  </div>
                </div>
              )}
              {available_options?.dimensions?.length > 0 && (
                <div>
                  <span className="text-[10px] text-[#4A7B76] font-bold uppercase tracking-wide block mb-2" style={{ fontFamily: 'DM Sans, sans-serif' }}>Available Dimensions</span>
                  <div className="flex flex-wrap gap-2">
                    {available_options.dimensions.map(d => (
                      <span key={d} className="px-3 py-1 rounded-[8px] text-xs text-[#0D9488] bg-[#0D9488]/10 font-mono shadow-sm">{d}</span>
                    ))}
                  </div>
                </div>
              )}
            </div>
          )}
        </div>
      </div>
    </div>
  );
}

/* ── Schema response panel ── */
function SchemaResponsePanel({ message }) {
  return (
    <div className="flex flex-col gap-4 animate-slide-in">
      <div
        className="flex items-start gap-4 p-6 rounded-[32px] backdrop-blur-xl border-l-4 border-[#0D9488]"
        style={{ background: 'rgba(255,255,255,0.65)', boxShadow: CLAY_SHADOW }}
      >
        <div className="bg-[#0D9488]/10 p-2 rounded-full shrink-0 mt-0.5">
          <Info size={18} className="text-[#0D9488]" />
        </div>
        <div>
          <p className="text-[#1A3A38] text-base font-bold mb-2" style={{ fontFamily: 'DM Sans, sans-serif' }}>What's available</p>
          <p className="text-[#4A7B76] text-sm whitespace-pre-line leading-relaxed" style={{ fontFamily: 'DM Sans, sans-serif' }}>{message}</p>
        </div>
      </div>
    </div>
  );
}

/* ── Out-of-scope panel ── */
function OutOfScopePanel({ message, suggestedQuery, onSuggestionClick }) {
  return (
    <div className="flex flex-col gap-4 animate-slide-in">
      <div
        className="flex items-start gap-4 p-6 rounded-[32px] backdrop-blur-xl border-l-4 border-[#F59E0B]"
        style={{ background: 'rgba(255,255,255,0.65)', boxShadow: CLAY_SHADOW }}
      >
        <div className="bg-[#F59E0B]/10 p-2 rounded-full shrink-0 mt-0.5">
          <Lightbulb size={18} className="text-[#F59E0B]" />
        </div>
        <div>
          <p className="text-[#1A3A38] text-base font-bold mb-2" style={{ fontFamily: 'DM Sans, sans-serif' }}>Try a data question</p>
          <p className="text-[#4A7B76] text-sm mb-4 leading-relaxed" style={{ fontFamily: 'DM Sans, sans-serif' }}>{message}</p>
          {suggestedQuery && onSuggestionClick && (
            <button
              onClick={() => onSuggestionClick(suggestedQuery)}
              className="inline-flex items-center gap-2 px-4 py-2 rounded-full text-xs font-bold text-[#0D9488] transition-all duration-200 hover:-translate-y-0.5"
              style={{ background: 'rgba(13,148,136,0.08)', boxShadow: '4px 4px 8px rgba(13,148,136,0.08), -3px -3px 6px rgba(255,255,255,0.9)', fontFamily: 'DM Sans, sans-serif' }}
              title="Click to populate the input field"
            >
              <ChevronRight size={12} />
              {suggestedQuery}
            </button>
          )}
        </div>
      </div>
    </div>
  );
}

/* ── Main export ── */
export default function QueryResultPanel({ response, error, defaultTab = 'Tabular Results', onSuggestionClick, isMostRecent = true }) {
  const [activeTab, setActiveTab] = useState(defaultTab);
  const [userExpanded, setUserExpanded] = useState(false);

  if (error) {
    return (
      <div
        className="flex items-start gap-4 p-6 rounded-[32px] backdrop-blur-xl animate-fade-in w-full"
        style={{ background: 'rgba(244,63,94,0.06)', boxShadow: '8px 8px 16px rgba(244,63,94,0.06), -6px -6px 12px rgba(255,255,255,0.9)' }}
      >
        <XCircle size={20} className="text-[#F43F5E] shrink-0 mt-0.5" />
        <div>
          <p className="text-[#F43F5E] font-bold font-dm text-base">
            {error.response?.data?.error
              ? `${error.response.data.error}: ${error.response.data.message}`
              : error.message || 'API request failed'}
          </p>
          {error.response?.data?.detail && (
            <pre className="mt-2 text-xs text-[#F43F5E]/70 font-mono whitespace-pre-wrap">
              {error.response.data.detail}
            </pre>
          )}
          {!error.response && (
            <p className="text-sm text-[#4A7B76] mt-1 font-dm">
              Could not reach the backend. Is the gateway running?
            </p>
          )}
        </div>
      </div>
    );
  }

  if (!response) return null;

  const { status, query, validation, governance, result, rejection } = response;
  const narrativeSummary = response.narrative_summary || '';
  const isRejected      = status === 'rejected';
  const isClarification = status === 'needs_clarification';
  const isSuccess       = status === 'success' || status === 'dry_run';
  const isSchema        = status === 'schema_response';
  const isOutOfScope    = status === 'out_of_scope';

  const isExpanded = isMostRecent || userExpanded;

  if (isClarification) return <ClarificationPanel response={response} />;
  if (isSchema) return <SchemaResponsePanel message={response.message} />;
  if (isOutOfScope) {
    return <OutOfScopePanel message={response.message} suggestedQuery={response.suggested_query} onSuggestionClick={onSuggestionClick} />;
  }

  // Handle collapsed state
  if (!isExpanded && isSuccess) {
    const firstSentence = narrativeSummary ? narrativeSummary.split('.')[0] + '.' : '';
    const metricText = query?.interpreted_metrics?.join(', ') || 'No metrics';
    const dimText = query?.interpreted_dimensions?.join(', ') || '';
    const byDimText = dimText ? `by ${dimText}` : '';
    
    return (
      <div 
        className="flex items-center gap-4 px-6 py-4 rounded-[24px] cursor-pointer hover:-translate-y-0.5 transition-all duration-200 backdrop-blur-xl w-full"
        style={{ background: 'rgba(255,255,255,0.65)', boxShadow: CLAY_SHADOW }}
        onClick={() => setUserExpanded(true)}
        title="Click to expand"
      >
        <div className="w-8 h-8 rounded-full flex items-center justify-center shrink-0 bg-emerald-50 shadow-inner">
          <CheckCircle2 size={16} className="text-emerald-500" />
        </div>
        <div className="flex items-center gap-3 text-sm text-[#1A3A38] font-dm truncate flex-1">
          <span className="font-bold text-[15px] truncate">{metricText}</span>
          {byDimText && <span className="text-neu-muted truncate">{byDimText}</span>}
          <span className="text-neu-muted px-3 py-1 bg-white/50 rounded-full shrink-0 shadow-sm">{result?.row_count ?? 0} rows</span>
          <span className="text-[#4A7B76] truncate ml-2 text-[13px]">{firstSentence}</span>
        </div>
        <ChevronRight size={18} className="text-[#0D9488] shrink-0" />
      </div>
    );
  }

  return (
    <div 
      className="flex flex-col backdrop-blur-xl rounded-[32px] overflow-hidden w-full animate-slide-in"
      style={{ background: 'rgba(255,255,255,0.7)', boxShadow: CLAY_SHADOW }}
    >
      {/* Premium Compact header row — success only */}
      {isSuccess && (
        <div 
          className="flex flex-wrap items-center gap-x-6 gap-y-3 px-8 py-5 text-sm font-dm"
          style={{ background: 'rgba(255,255,255,0.4)', borderBottom: '1px solid rgba(13,148,136,0.1)' }}
        >
          <div className="flex items-center gap-3 shrink-0">
            <CheckCircle2 size={18} className="text-emerald-500" />
            <StatusBadge status={status} label={status.replace('_', ' ')} />
          </div>
          
          <div className="flex items-center gap-3 border-l border-[#0D9488]/10 pl-6 truncate">
            <span className="text-[#4A7B76] text-xs uppercase font-bold tracking-wider shrink-0">Metrics</span>
            <span className="font-bold text-[#1A3A38] text-[15px] truncate">{query?.interpreted_metrics?.join(', ') || '—'}</span>
          </div>

          <div className="flex items-center gap-3 border-l border-[#0D9488]/10 pl-6 truncate">
            <span className="text-[#4A7B76] text-xs uppercase font-bold tracking-wider shrink-0">Dims</span>
            <span className="font-bold text-[#1A3A38] text-[15px] truncate">{query?.interpreted_dimensions?.join(', ') || '—'}</span>
          </div>

          <div className="flex items-center gap-3 border-l border-[#0D9488]/10 pl-6 shrink-0">
            <span className="text-[#4A7B76] text-xs uppercase font-bold tracking-wider">Rows</span>
            <span className="font-bold text-[#1A3A38] text-[15px] bg-white/60 px-2.5 py-0.5 rounded-full shadow-sm">{result?.row_count ?? 0}</span>
          </div>

          <div className="flex items-center gap-3 border-l border-[#0D9488]/10 pl-6 truncate">
            <span className="text-[#4A7B76] text-xs uppercase font-bold tracking-wider shrink-0">Time</span>
            <span className="font-bold text-[#1A3A38] text-[15px] truncate">{query?.time_range ? `${query.time_range.start_date} → ${query.time_range.end_date}` : '—'}</span>
          </div>

          {response.cache_hit === true && (
            <div className="ml-auto shrink-0 pl-2">
              <span className="inline-flex items-center gap-1.5 px-3 py-1 rounded-[8px] text-[11px] font-bold text-[#0D9488] bg-teal-50 border border-teal-100" title="This result was served from cache">
                <Database size={12} /> Cached
              </span>
            </div>
          )}
        </div>
      )}

      {/* Rejection detail */}
      {isRejected && (
        <div className="p-8 border-b border-[#D1E2DE]/50">
          <RejectionPanel rejection={rejection} />
        </div>
      )}

      {/* Tabbed panels — success */}
      {isSuccess && (
        <div className="flex flex-col">
          <div className="px-8 pt-6 pb-0">
            <Tabs
              tabs={['Summary', 'Tabular Results', 'Governance', 'SQL', 'Lineage']}
              active={activeTab}
              onSelect={setActiveTab}
            />
          </div>
          <div className="p-8 pt-6">
            {activeTab === 'Summary'    && <NarrativeSummary text={narrativeSummary} query={query?.original_query || ''} lineagePath={governance?.lineage_path} />}
            {activeTab === 'Tabular Results'    && <ResultsTable data={result?.data} />}
            {activeTab === 'Governance' && <GovernancePanel governance={governance} validation={validation} />}
            {activeTab === 'SQL'        && (
              <SqlViewer
                generatedSql={result?.generated_sql}
                metricflowQuery={result?.metricflow_query}
              />
            )}
            {activeTab === 'Lineage'   && (
              <div className="flex flex-col gap-6">
                <LineageGraph path={governance?.lineage_path} steps={[]} />
                {governance?.lineage_path?.length > 0 && (
                  <div className="overflow-x-auto rounded-[20px]" style={{ boxShadow: CLAY_INSET }}>
                    <table className="w-full text-sm font-dm">
                      <thead>
                        <tr className="bg-[rgba(255,255,255,0.4)] border-b border-[#D1E2DE]/50">
                          <th className="px-4 py-3 text-left text-xs font-mono text-neu-muted uppercase tracking-wide">Step</th>
                          <th className="px-4 py-3 text-left text-xs font-mono text-neu-muted uppercase tracking-wide">Model</th>
                          <th className="px-4 py-3 text-left text-xs font-mono text-neu-muted uppercase tracking-wide">Layer</th>
                        </tr>
                      </thead>
                      <tbody className="divide-y divide-[#D1E2DE]/40">
                        {governance.lineage_path.map((m, i) => {
                          const isLast = i === governance.lineage_path.length - 1;
                          return (
                            <tr key={i} className="hover:bg-[rgba(255,255,255,0.5)] transition-colors">
                              <td className="px-4 py-3 text-neu-muted font-mono text-xs">{i + 1}</td>
                              <td className="px-4 py-3">
                                <code className={`text-[13px] font-mono ${isLast ? 'text-[#0D9488] font-bold' : 'text-[#1A3A38]'}`}>{m}</code>
                              </td>
                              <td className="px-4 py-3">
                                <StatusBadge
                                  status={isLast ? 'certified' : 'info'}
                                  label={isLast ? 'metric' : m.startsWith('stg_') ? 'staging' : m.startsWith('int_') ? 'intermediate' : m.startsWith('fct_') || m.startsWith('dim_') ? 'marts' : 'raw'}
                                />
                              </td>
                            </tr>
                          );
                        })}
                      </tbody>
                    </table>
                  </div>
                )}
              </div>
            )}
          </div>
        </div>
      )}

      {response?.request_id && (
        <div className="px-8 py-3 bg-[rgba(255,255,255,0.3)] border-t border-[#0D9488]/10 flex justify-between items-center">
          <p className="text-[10px] text-[#4A7B76] font-mono opacity-60">request_id: {response.request_id}</p>
        </div>
      )}
    </div>
  );
}
